# Docker Compose for development with the UC Core Simulator
version: '3.4'
name: integration-channels

services:
  # Your integration service
  intg-channels:
    image: ghcr.io/jackjpowell/uc-intg-channels:latest
    container_name: intg-channels
    network_mode: host
    environment:
      - UC_INTEGRATION_HTTP_PORT=9090
    volumes:
      - ./intg-channels:/config
    restart: unless-stopped
